version: "3.9"

networks:
  myportfolio-net:

services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    networks:
      - myportfolio-net
    depends_on:
      mysql:
        condition: service_healthy # <-- This now waits for the healthcheck

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql
    networks:
      - myportfolio-net
    healthcheck: # <-- This section is new
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=shloktomar65@gmail.com
      - CERTBOT_DOMAINS=shloktomar.duckdns.org
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    networks:
      - myportfolio-net
    depends_on:
      - myportfolio

volumes:
  mydatabase:
  nginx_secrets:

